### ISSUE TITLE
输入全0的wavdata，python返回结果和c++返回结果不一致

### ISSUE THREAD

**Issue by masimeng1994** [csukuangfj/kaldi-native-fbank#10]
c++返回的结果全是-inf
python返回结果为-100.0，如图
![image](https://user-images.githubusercontent.com/24523981/211486797-bcbc74d8-76a9-4b95-9d9e-ec3f81f5a09b.png)

两个都是使用的下面这个配置
![image](https://user-images.githubusercontent.com/24523981/211486965-324e2b74-a8f7-41ff-99a6-53ce381a7cb9.png)
请问，c++需要额外配置什么配置吗？

**Comment by csukuangfj** [comment]
可以把 c++ 和 python 的测试代码，完整的发出来么？

**Comment by masimeng1994** [comment]
理论上如果接口返回全0就正确了吧

**Comment by csukuangfj** [comment]
输入全 0 ，会有直流分量。返回的特征，不会是全0的。
