### ISSUE TITLE
请问，这里面包含了kaldi中的compute-fbank-feats的实现么

### ISSUE THREAD

**Issue by quliulangle** [csukuangfj/kaldi-native-fbank#39]
如题

**Comment by quliulangle** [comment]
纯小白，我看compute-fbank-feats相关的实现是在FrameExtractionOptions这里面，但是Python的接口只有as_dict(),from_dict（）这几个属性，那怎么使用才能得到kaldi一样的结果呢

**Comment by csukuangfj** [comment]
> ，但是Python的接口只有as_dict(),from_dict（）这几个属性

你这个， 只有，是从哪里看到的？

https://github.com/csukuangfj/kaldi-native-fbank/tree/master/kaldi-native-fbank/python/tests

这里有例子的
