### ISSUE TITLE
支持WhisperFeatureComputer配置mel_opts.num_bins参数

### ISSUE THREAD

**Issue by yang-441** [csukuangfj/kaldi-native-fbank#47]
whisper-largev3 频率滤波器的数量增加到了128, 但是配置写死, 无法自定义调整

**Comment by yang-441** [comment]
https://github.com/csukuangfj/kaldi-native-fbank/blob/master/kaldi-native-fbank/csrc/whisper-feature.cc

**Comment by csukuangfj** [comment]
马上

**Comment by csukuangfj** [comment]
@yang-441 
请帮忙测一下 v1.20.0

```
pip install kaldi-native-fbank==1.20.0
```

然后参考
https://github.com/csukuangfj/kaldi-native-fbank/blob/af5968505a23dfe139540d20d435290b31e8a013/kaldi-native-fbank/python/tests/test_online_whisper_fbank.py#L12-L17
