### ISSUE TITLE
hi,请问有没有现成的android JNI 呀？

### ISSUE THREAD

**Issue by hehr** [csukuangfj/kaldi-native-fbank#49]
RT ,想直接找个轮子用一下 ....

**Comment by csukuangfj** [comment]
你可以看
https://github.com/k2-fsa/sherpa-onnx

kaldi-native-fbank , 是作为其他项目一部分被调用的。

特征处理这块，对用户是不可见的，我们不提供 jni 的接口。

**Comment by hehr** [comment]
好的，我研究一下，先谢了
