### ISSUE TITLE
C API

### ISSUE THREAD

**Issue by thewh1teagle** [csukuangfj/kaldi-native-fbank#50]
Hey
I would like to use it from Rust. However it doesn't work well with C++.
Could you expose c-api like with sherpa-onnx?
Thanks

By the way I tried to compare native fbank with `torchaudio.compliance.kaldi` and seems like something is wrong with native fbank it's not identical. 
I test it on nemo speaker embedding. with `torchaudio` fbank I get good results. with native fbank it's not correct.

<details>
<summary>log</summary>

There are 5 speakers in the audio file. it's 16khz mono.

```console
python main.py
--- Pytorch kaldi fbank ---
{'start': 0.788, 'end': 3.994, 'speaker': 1}
{'start': 4.348, 'end': 7.892, 'speaker': 1}
{'start': 9.816, 'end': 14.828, 'speaker': 2}
{'start': 17.106, 'end': 28.193, 'speaker': 3}
{'start': 29.475, 'end': 31.669, 'speaker': 4}
{'start': 32.529, 'end': 33.019, 'speaker': 5}
{'start': 33.458, 'end': 36.242, 'speaker': 4}
{'start': 39.229, 'end': 42.03, 'speaker': 5}
{'start': 46.907, 'end': 48.544, 'speaker': 1}
{'start': 48.848, 'end': 51.294, 'speaker': 1}
--- Native fbank ---
{'start': 0.788, 'end': 3.994, 'speaker': 1}
{'start': 4.348, 'end': 7.892, 'speaker': 1}
{'start': 9.816, 'end': 14.828, 'speaker': 2}
{'start': 17.106, 'end': 28.193, 'speaker': 2}
{'start': 29.475, 'end': 31.669, 'speaker': 2}
{'start': 32.529, 'end': 33.019, 'speaker': 1}
{'start': 33.458, 'end': 36.242, 'speaker': 2}
{'start': 39.229, 'end': 42.03, 'speaker': 2}
{'start': 46.907, 'end': 48.544, 'speaker': 2}
{'start': 48.848, 'end': 51.294, 'speaker': 2}
```
</details> 

<details>
<summary>plots</summary>

<img width=400 src="https://github.com/user-attachments/assets/1d90f090-b35f-44d2-af16-f396e591b333">
<img width=400 src="https://github.com/user-attachments/assets/6eb980d6-32c1-479d-bed0-5628ce9d93b8">

</details>

*The compute function is [here](https://github.com/thewh1teagle/ort-diarize/blob/feat/native-fbank/extract.py#L63)*
*The program source is [here](https://github.com/thewh1teagle/ort-diarize/blob/feat/native-fbank/main.py)*

**Comment by csukuangfj** [comment]
1. It is usually used as a subproject so we don't plan to add C api for it.


2. Make sure your are using the same parameters as torchaudio.
Don't use default parameters!

Believe me that as long as you use identical parameters, you should get identical results if you give the same input.

**Comment by csukuangfj** [comment]
Apparently, you are not using the same input for testing and you are not using the same parameters for computing

To give you two examples,

 - 1. torchaudio is using samples in the range [-32768, 32767] while kaldi_native_fbank is using [-1, 1]
 - 2. torchaudio is using the hamming window

Please check the code carefully by yourself.

**Comment by thewh1teagle** [comment]
> Apparently, you are not using the same input for testing and you are not using the same parameters for computing

Thanks that helped me find it. I inspected it deeply and compared until it was identical input.
Then the features was identical.
I created [pyannote-rs](https://github.com/thewh1teagle/pyannote-rs) for diarization and it turned to be very accurate (Like pyannote).
Maybe you'll find it useful for adapting it to sherpa-onnx

**Comment by thewh1teagle** [comment]
Is there a way I can control kaldi-native-fbank so it will link msvc dynamically?
When trying to link my project with msvc dynamic I get the error

```console
mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in libknf_rs_sys-7965f34deb79ccd6.rlib(knfc.obj)
```

Maybe the problem is in the [wrapper](https://github.com/thewh1teagle/knf-rs/blob/main/sys/knfc/CMakeLists.txt) I wrote

**Comment by csukuangfj** [comment]
please pass `-DBUILD_SHARED_LIBS=ON` to `cmake`.

**Comment by Baiyuetribe** [comment]
@thewh1teagle 
same issue. fixed with:
`cmake -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DCMAKE_CXX_FLAGS_RELEASE="/MT" -DCMAKE_C_FLAGS_RELEASE="/MT" ..`
