### ISSUE TITLE
方便指导一下jni或者online的实现原理，离线部分参照whisper，pytorch等python代码基本可以复现，但是实时部分看不懂

### ISSUE THREAD

**Issue by tiandiweizun** [csukuangfj/kaldi-native-fbank#53]
如题。

**Comment by csukuangfj** [comment]
不好意思，看不懂你的问题

**Comment by tiandiweizun** [comment]
我看了历史的issue，你说了jni参照另外一个项目，不方便直接提供，我需要java编程，本身是为了调用funasr里面的vad模型，那个vad模型用了kaldi-native-fbank的online模式提取fbank，由于本身不懂c++,确实看不懂，虽然offline模式的fbank有不少其它的项目可以参考的python或者java实现代码，但是online匮乏，**所以希望知道kaldi-native-fbank 的online的相较于offline有哪些不一样的流程，这样方便直接使用java写一套**。
