### ISSUE TITLE
高版本android ndk编译.c文件不编译

### ISSUE THREAD

**Issue by masimeng1994** [csukuangfj/kaldi-native-fbank#9]
我用的android-ndk-r19c，编译时候发现缺少rdft，查看编译log发现，fftsg.c没有编译进去
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/24523981/210940661-16f222e1-8262-4167-93f2-30942e5f8f8f.png">

<img width="813" alt="image" src="https://user-images.githubusercontent.com/24523981/210940604-05e51db2-2eaa-4bac-b53f-7b51fba7dbbf.png">
我的编译命令是这样的
cmake -DCMAKE_TOOLCHAIN_FILE=$ndk_dir/build/cmake/android.toolchain.cmake \
              -DARCH=${target} \
              -DANDROID_TOOLCHAIN=clang -DANDROID_ABI=${ABI} -DANDROID_PLATFORM=android-21 \
              -DCMAKE_BUILD_TYPE=${build_type} ../../../

**Comment by masimeng1994** [comment]
> 我用的android-ndk-r19c，编译时候发现缺少rdft，查看编译log发现，fftsg.c没有编译进去 <img alt="image" width="1017" src="https://user-images.githubusercontent.com/24523981/210940661-16f222e1-8262-4167-93f2-30942e5f8f8f.png">
> 
> <img alt="image" width="813" src="https://user-images.githubusercontent.com/24523981/210940604-05e51db2-2eaa-4bac-b53f-7b51fba7dbbf.png">
> 
> 我的编译命令是这样的

**Comment by csukuangfj** [comment]
解决了么？

**Comment by masimeng1994** [comment]
还没有

**Comment by csukuangfj** [comment]
你的具体命令是什么？你是怎么用这个 project 的？

你给的 error log， 包含的信息量非常少。

**Comment by csukuangfj** [comment]
有更多的log没

**Comment by masimeng1994** [comment]
我是包在自己工程里编的，可能在哪些地方设置了忽略.c。我试了下把kaldi-native-fbank单拿出来编是可以编的。

**Comment by masimeng1994** [comment]
解决了，发现CMakeLists里这行设置了CXX，导致没编.c
project(speechx LANGUAGES CXX)

**Comment by csukuangfj** [comment]
> 解决了，发现CMakeLists里这行设置了CXX，导致没编.c project(speechx LANGUAGES CXX)

解决了就好

**Comment by zll961020** [comment]
请问作者，这个库依赖onnx吗，我看了一下sherpa-onnx库的编译shell脚本，有一些关于onnx的选项，具体如何在安卓平台上编译这个库呢，

**Comment by csukuangfj** [comment]
这个是纯c++的项目，除了依赖c++，不依赖其他第三方库，更加不依赖onnx


如何编译，是基本的编程知识，建议自己努力学习。

**Comment by zll961020** [comment]
感谢回复，已经解决了。
